backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow
search: true
collections:
  - name: blog
    label: Blog
    label_singular: post
    path: "{{slug}}/index.en"
    folder: content/blog
    create: true
    filter: {field: visibleInCMS, value: true}
    fields: [
      {name: title, widget: string},
      {name: description, widget: text},
      {name: date, widget: datetime},
      {name: body, widget: markdown},
      {name: thumbnail, widget: image, required: false},
      {name: visibleInCMS, widget: hidden, default: true}
    ]
  - name: "guides" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Guides" # Used in the UI, ie.: "New Post"
    folder: "content/guides" # The path to the folder where the documents are stored
    path: "{{slug}}/index.en" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
#  - name: "blog" # Used in routes, e.g., /admin/collections/blog
#    label: "Blog" # Used in the UI
#    folder: "content/blog" # The path to the folder where the documents are stored
#    create: true # Allow users to create new documents in this collection
##    identifier_field: name
#    slug: "{{slug}}-{{day}}-{{month}}-{{year}}" # Filename template, e.g., YYYY-MM-DD-title.md
#    fields: # The fields for each document, usually in front matter
#      - { label: "Layout", name: "layout", widget: "string", default: "blog" }
#      - { label: "Title", name: "title", widget: "string" }
#      - { label: "Publish Date", name: "date", widget: "datetime" }
#      - { label: "Featured Image", name: "thumbnail", widget: "image" }
##      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
#      - { label: "Body", name: "body", widget: "markdown" }