backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

slug:
  encoding: "ascii"
  clean_accents: true

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow
search: true
collections:
  - name: blog
    label: Blog
    label_singular: blog
    folder: content/blog
    path: "{{slug}}/index"
    create: true
    filter: {field: visibleInCMS, value: true}
    fields: [
      {name: title, widget: string},
      {name: description, widget: text},
      {name: image, widget: image, required: false},
      {name: body, widget: markdown},
      {name: time, widget: datetime, date_format: "DD.MM.YYYY", time_format: "HH.mm", format: LLL, default: "{{now}}"},
      {name: visibleInCMS, widget: hidden, default: true}
      ]
  - name: guides
    label: Guides
    label_singular: guides
    folder: content/guides
    slug: 'index'
    path: '{{title}}/{{slug}}.en'
    create: true
    filter: {field: visibleInCMS, value: true}
    fields: 
    - label: "Title"
      name: "title" 
      widget: "string"
    - name: "description" 
      widget: "text"
    - label: "Start time"
      name: "start"
      widget: "datetime"
      date_format: "DD.MM.YYYY" # e.g. 24.12.2021
      time_format: "HH:mm" # e.g. 21:07
    - label: "Image"
      name: "image"
      widget: "image"
      required: false
    - label: "Body"
      name: "body"
      widget: "markdown"
    - label: "visible"
      name: "visibleInCMS" 
      widget: "hidden"
      default: true

#  - name: "blog" # Used in routes, e.g., /admin/collections/blog
#    label: "Blog" # Used in the UI
#    folder: "content/blog" # The path to the folder where the documents are stored
#    create: true # Allow users to create new documents in this collection
##    identifier_field: name
#    slug: "{{slug}}-{{day}}-{{month}}-{{year}}" # Filename template, e.g., YYYY-MM-DD-title.md
#    fields: # The fields for each document, usually in front matter
#      - { label: "Layout", name: "layout", widget: "string", default: "blog" }
#      - { label: "Title", name: "title", widget: "string" }
#      - { label: "Publish Date", name: "date", widget: "datetime" }
#      - { label: "Featured Image", name: "thumbnail", widget: "image" }
##      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
#      - { label: "Body", name: "body", widget: "markdown" }